.github/PULL_REQUEST_TEMPLATE.md, src/spaceone/file_manager/connector/aws_s3_connector.py
Change expiration time when downloading files
=> Change expiration time when downloading files

src/spaceone/file_manager/interface/rest/files.py
refactor: remove unused imports in files.py
=> refactor: remove unused imports in files.py

src/spaceone/file_manager/model/__init__.py
=> refactor: import file database model

src/spaceone/file_manager/model/__init__.py
feat: add UserFile model import to file manager
=> feat: add UserFile model import to file manager

.gitignore
- [] New feature
feat: update .gitignore to exclude .vscode and add initial test file
=> feat: update .gitignore to exclude .vscode and add initial test file

src/spaceone/file_manager/service/user_file_service.py
[fix: add error handling for missing file in user_file_service]
=> fix: add error handling for missing file in user_file_service

src/spaceone/file_manager/interface/rest/file.py, src/spaceone/file_manager/manager/file_manager.py, src/spaceone/file_manager/manager/identity_manager.py, src/spaceone/file_manager/model/file/database.py, src/spaceone/file_manager/model/file/request.py, src/spaceone/file_manager/model/file/response.py, src/spaceone/file_manager/service/file_service.py
refactor: remove project_id references and update workspace handling
=> refactor: remove project_id references and update workspace handling

deploy/helm/config/nginx.conf, src/spaceone/file_manager/connector/aws_s3_connector.py, src/spaceone/file_manager/connector/file_base_connector.py, src/spaceone/file_manager/connector/minio_connector.py, src/spaceone/file_manager/interface/grpc/user_file.py, src/spaceone/file_manager/interface/rest/file.py, src/spaceone/file_manager/interface/rest/user_file.py, src/spaceone/file_manager/manager/file_connector_manager.py, src/spaceone/file_manager/manager/file_manager.py, src/spaceone/file_manager/manager/identity_manager.py, src/spaceone/file_manager/manager/user_file_manager.py, src/spaceone/file_manager/model/file/database.py, src/spaceone/file_manager/model/file/request.py, src/spaceone/file_manager/model/file/response.py, src/spaceone/file_manager/model/user_file/database.py, src/spaceone/file_manager/model/user_file/request.py, src/spaceone/file_manager/model/user_file/response.py, src/spaceone/file_manager/service/file_service.py, src/spaceone/file_manager/service/user_file_service.py
feat: refactoring , added nginx  body size
=> feat: refactoring , added nginx  body size 

src/spaceone/file_manager/connector/aws_s3_connector.py, src/spaceone/file_manager/interface/grpc/user_file.py, src/spaceone/file_manager/interface/rest/file.py, src/spaceone/file_manager/interface/rest/user_file.py, src/spaceone/file_manager/manager/identity_manager.py, src/spaceone/file_manager/manager/user_file_manager.py, src/spaceone/file_manager/model/user_file/response.py, src/spaceone/file_manager/service/user_file_service.py
refactor: update user file management methods and response structures
=> refactor: update user file management methods and response structures

src/spaceone/file_manager/service/user_file_service.py
fix: correct parameter formatting in get_user_file method
=> fix: correct parameter formatting in get_user_file method

deploy/helm/config/nginx.conf
feat: add charset utf-8 to nginx configuration
=> feat: add charset utf-8 to nginx configuration

src/spaceone/file_manager/model/file/request.py, src/spaceone/file_manager/service/file_service.py
feat: refactor resource group handling based on user role in file service
=> feat: refactor resource group handling based on user role in file service

src/spaceone/file_manager/interface/rest/file.py
feat: add optional project_id parameter to upload_project_file endpoint
=> feat: add optional project_id parameter to upload_project_file endpoint

src/spaceone/file_manager/interface/rest/file.py
=> feat: improve filename handling in file download response

src/spaceone/file_manager/manager/file_manager.py, src/spaceone/file_manager/service/file_service.py
feat: remove commented-out project_id parameter from file retrieval
=> feat: remove commented-out project_id parameter from file retrieval

src/spaceone/file_manager/model/file/database.py
feat: add project_id to updatable_fields in File model
=> feat: add project_id to updatable_fields in File model

src/spaceone/file_manager/conf/global_conf.py, src/spaceone/file_manager/manager/file_manager.py, src/spaceone/file_manager/model/file/response.py, src/spaceone/file_manager/model/user_file/response.py, src/spaceone/file_manager/service/file_service.py, src/spaceone/file_manager/service/user_file_service.py
- [] Bug fix
feat: fix download URL construction and improve user file response handling
=> feat: fix download URL construction and improve user file response handling

src/spaceone/file_manager/interface/rest/file.py
feat: update resource group parameter from WORKSPACE to PROJECT and add initial test file
=> feat: update resource group parameter from WORKSPACE to PROJECT and add initial test file

src/spaceone/file_manager/interface/rest/file.py
feat: remove resource_group parameter from download_file and upload_file methods
=> feat: remove resource_group parameter from download_file and upload_file methods

pkg/pip_requirements.txt, src/spaceone/file_manager/conf/global_conf.py, src/spaceone/file_manager/connector/aws_s3_connector.py, src/spaceone/file_manager/connector/minio_connector.py, src/spaceone/file_manager/interface/rest/file.py, src/spaceone/file_manager/interface/rest/user_file.py
feat: enhance MinIO connector with improved file upload/download handling and logging
=> feat: enhance MinIO connector with improved file upload/download handling and logging
